name: flextensions
description: Extension methods for Flutter and Dart
version: 0.2.1
homepage: https://github.com/xiprox/flextensions

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: