name: Deploy

on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  deploy:
    name: Deploy package
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@main
